/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacymanagement;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author SIWMI
 */
public class Owner extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Owner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanelTab = new javax.swing.JPanel();
        tabEmp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabDep = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tabSup = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tabWel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tabAtt = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabPay = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tabPur = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tabTra = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tabRep = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tabLogOut = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tabLvs = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tabAddExp = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jPanelEmp = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanelAddExp = new javax.swing.JPanel();
        jPanelDep = new javax.swing.JPanel();
        jPanelSup = new javax.swing.JPanel();
        jPanelLvs = new javax.swing.JPanel();
        jPanelWel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanelAtt = new javax.swing.JPanel();
        jPanelPay = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanelPur = new javax.swing.JPanel();
        jPanelTra = new javax.swing.JPanel();
        jPanelRep = new javax.swing.JPanel();
        jPanelLogOut = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTab.setBackground(new java.awt.Color(202, 228, 255));

        tabEmp.setBackground(new java.awt.Color(0, 153, 204));
        tabEmp.setPreferredSize(new java.awt.Dimension(110, 54));
        tabEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabEmpMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Manage Employee");

        javax.swing.GroupLayout tabEmpLayout = new javax.swing.GroupLayout(tabEmp);
        tabEmp.setLayout(tabEmpLayout);
        tabEmpLayout.setHorizontalGroup(
            tabEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEmpLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabEmpLayout.setVerticalGroup(
            tabEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabDep.setBackground(new java.awt.Color(0, 153, 204));
        tabDep.setPreferredSize(new java.awt.Dimension(110, 55));
        tabDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDepMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Manage Dependant");

        javax.swing.GroupLayout tabDepLayout = new javax.swing.GroupLayout(tabDep);
        tabDep.setLayout(tabDepLayout);
        tabDepLayout.setHorizontalGroup(
            tabDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        tabDepLayout.setVerticalGroup(
            tabDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSup.setBackground(new java.awt.Color(0, 153, 204));
        tabSup.setPreferredSize(new java.awt.Dimension(110, 56));
        tabSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSupMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Manage Supplier");

        javax.swing.GroupLayout tabSupLayout = new javax.swing.GroupLayout(tabSup);
        tabSup.setLayout(tabSupLayout);
        tabSupLayout.setHorizontalGroup(
            tabSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSupLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabSupLayout.setVerticalGroup(
            tabSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabWel.setBackground(new java.awt.Color(0, 153, 204));
        tabWel.setPreferredSize(new java.awt.Dimension(110, 56));
        tabWel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabWelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Manage Welfare");

        javax.swing.GroupLayout tabWelLayout = new javax.swing.GroupLayout(tabWel);
        tabWel.setLayout(tabWelLayout);
        tabWelLayout.setHorizontalGroup(
            tabWelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabWelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabWelLayout.setVerticalGroup(
            tabWelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabWelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAtt.setBackground(new java.awt.Color(0, 153, 204));
        tabAtt.setPreferredSize(new java.awt.Dimension(110, 56));
        tabAtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAttMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Attendance");

        javax.swing.GroupLayout tabAttLayout = new javax.swing.GroupLayout(tabAtt);
        tabAtt.setLayout(tabAttLayout);
        tabAttLayout.setHorizontalGroup(
            tabAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAttLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabAttLayout.setVerticalGroup(
            tabAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPay.setBackground(new java.awt.Color(0, 153, 204));
        tabPay.setPreferredSize(new java.awt.Dimension(110, 55));
        tabPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPayMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Salaries");

        javax.swing.GroupLayout tabPayLayout = new javax.swing.GroupLayout(tabPay);
        tabPay.setLayout(tabPayLayout);
        tabPayLayout.setHorizontalGroup(
            tabPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPayLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabPayLayout.setVerticalGroup(
            tabPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPur.setBackground(new java.awt.Color(0, 153, 204));
        tabPur.setPreferredSize(new java.awt.Dimension(110, 56));
        tabPur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPurMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Purchase Orders");

        javax.swing.GroupLayout tabPurLayout = new javax.swing.GroupLayout(tabPur);
        tabPur.setLayout(tabPurLayout);
        tabPurLayout.setHorizontalGroup(
            tabPurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPurLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabPurLayout.setVerticalGroup(
            tabPurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabTra.setBackground(new java.awt.Color(0, 153, 204));
        tabTra.setPreferredSize(new java.awt.Dimension(110, 56));
        tabTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTraMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Transactions");

        javax.swing.GroupLayout tabTraLayout = new javax.swing.GroupLayout(tabTra);
        tabTra.setLayout(tabTraLayout);
        tabTraLayout.setHorizontalGroup(
            tabTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTraLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabTraLayout.setVerticalGroup(
            tabTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabRep.setBackground(new java.awt.Color(0, 153, 204));
        tabRep.setPreferredSize(new java.awt.Dimension(110, 56));
        tabRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabRepMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Reports");

        javax.swing.GroupLayout tabRepLayout = new javax.swing.GroupLayout(tabRep);
        tabRep.setLayout(tabRepLayout);
        tabRepLayout.setHorizontalGroup(
            tabRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRepLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabRepLayout.setVerticalGroup(
            tabRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabLogOut.setBackground(new java.awt.Color(0, 153, 204));
        tabLogOut.setPreferredSize(new java.awt.Dimension(110, 56));
        tabLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabLogOutMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Log Out");

        javax.swing.GroupLayout tabLogOutLayout = new javax.swing.GroupLayout(tabLogOut);
        tabLogOut.setLayout(tabLogOutLayout);
        tabLogOutLayout.setHorizontalGroup(
            tabLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLogOutLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabLogOutLayout.setVerticalGroup(
            tabLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabLogOutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
        );

        tabLvs.setBackground(new java.awt.Color(0, 153, 204));
        tabLvs.setPreferredSize(new java.awt.Dimension(110, 56));
        tabLvs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabLvsMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Leaves");

        javax.swing.GroupLayout tabLvsLayout = new javax.swing.GroupLayout(tabLvs);
        tabLvs.setLayout(tabLvsLayout);
        tabLvsLayout.setHorizontalGroup(
            tabLvsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLvsLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabLvsLayout.setVerticalGroup(
            tabLvsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLvsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAddExp.setBackground(new java.awt.Color(0, 153, 204));
        tabAddExp.setPreferredSize(new java.awt.Dimension(110, 56));
        tabAddExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAddExpMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Additional Expenses");

        javax.swing.GroupLayout tabAddExpLayout = new javax.swing.GroupLayout(tabAddExp);
        tabAddExp.setLayout(tabAddExpLayout);
        tabAddExpLayout.setHorizontalGroup(
            tabAddExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddExpLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabAddExpLayout.setVerticalGroup(
            tabAddExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddExpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanelTabLayout = new javax.swing.GroupLayout(jPanelTab);
        jPanelTab.setLayout(jPanelTabLayout);
        jPanelTabLayout.setHorizontalGroup(
            jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabDep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabSup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabRep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabPur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabLvs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabAtt, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabWel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tabAddExp, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTabLayout.setVerticalGroup(
            jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tabEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabDep, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabSup, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabWel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabLvs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabPay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabAddExp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabPur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabTra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabRep, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanelHome.setBackground(new java.awt.Color(204, 204, 204));

        jPanelEmp.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel12.setText("EMPLOYEE MANAGEMENT");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("1. Jayasinghe Arachchige Siwmini Upamali");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Delete");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("2. Lukkuwaduge Hashini Mahinsa Fernando");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Delete");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("3. Ranasooriya Arachchige Dona Hansani Saranya");

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("Edit");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setText("+ Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagement/logo-color.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelEmpLayout = new javax.swing.GroupLayout(jPanelEmp);
        jPanelEmp.setLayout(jPanelEmpLayout);
        jPanelEmpLayout.setHorizontalGroup(
            jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelEmpLayout.createSequentialGroup()
                        .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelEmpLayout.createSequentialGroup()
                                    .addComponent(jButton5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6))
                                .addGroup(jPanelEmpLayout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addGroup(jPanelEmpLayout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addGap(48, 48, 48)
                                    .addComponent(jButton4)))))))
        );
        jPanelEmpLayout.setVerticalGroup(
            jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpLayout.createSequentialGroup()
                .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jLabel13))
                .addGap(35, 35, 35)
                .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33)
                .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(26, 26, 26)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAddExpLayout = new javax.swing.GroupLayout(jPanelAddExp);
        jPanelAddExp.setLayout(jPanelAddExpLayout);
        jPanelAddExpLayout.setHorizontalGroup(
            jPanelAddExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelAddExpLayout.setVerticalGroup(
            jPanelAddExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );

        jPanelDep.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanelDepLayout = new javax.swing.GroupLayout(jPanelDep);
        jPanelDep.setLayout(jPanelDepLayout);
        jPanelDepLayout.setHorizontalGroup(
            jPanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        jPanelDepLayout.setVerticalGroup(
            jPanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );

        jPanelSup.setBackground(new java.awt.Color(153, 153, 153));

        jPanelLvs.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanelLvsLayout = new javax.swing.GroupLayout(jPanelLvs);
        jPanelLvs.setLayout(jPanelLvsLayout);
        jPanelLvsLayout.setHorizontalGroup(
            jPanelLvsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        jPanelLvsLayout.setVerticalGroup(
            jPanelLvsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelSupLayout = new javax.swing.GroupLayout(jPanelSup);
        jPanelSup.setLayout(jPanelSupLayout);
        jPanelSupLayout.setHorizontalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSupLayout.setVerticalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLvs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelWel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagement/logo-color.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelWelLayout = new javax.swing.GroupLayout(jPanelWel);
        jPanelWel.setLayout(jPanelWelLayout);
        jPanelWelLayout.setHorizontalGroup(
            jPanelWelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWelLayout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );
        jPanelWelLayout.setVerticalGroup(
            jPanelWelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(721, 721, 721))
        );

        jPanelAtt.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanelAttLayout = new javax.swing.GroupLayout(jPanelAtt);
        jPanelAtt.setLayout(jPanelAttLayout);
        jPanelAttLayout.setHorizontalGroup(
            jPanelAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        jPanelAttLayout.setVerticalGroup(
            jPanelAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );

        jPanelPay.setBackground(new java.awt.Color(51, 255, 0));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagement/logo-color.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPayLayout = new javax.swing.GroupLayout(jPanelPay);
        jPanelPay.setLayout(jPanelPayLayout);
        jPanelPayLayout.setHorizontalGroup(
            jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPayLayout.createSequentialGroup()
                .addGap(0, 587, Short.MAX_VALUE)
                .addComponent(jLabel19))
        );
        jPanelPayLayout.setVerticalGroup(
            jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPayLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 727, Short.MAX_VALUE))
        );

        jPanelPur.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanelPurLayout = new javax.swing.GroupLayout(jPanelPur);
        jPanelPur.setLayout(jPanelPurLayout);
        jPanelPurLayout.setHorizontalGroup(
            jPanelPurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        jPanelPurLayout.setVerticalGroup(
            jPanelPurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );

        jPanelTra.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanelTraLayout = new javax.swing.GroupLayout(jPanelTra);
        jPanelTra.setLayout(jPanelTraLayout);
        jPanelTraLayout.setHorizontalGroup(
            jPanelTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        jPanelTraLayout.setVerticalGroup(
            jPanelTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );

        jPanelRep.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout jPanelRepLayout = new javax.swing.GroupLayout(jPanelRep);
        jPanelRep.setLayout(jPanelRepLayout);
        jPanelRepLayout.setHorizontalGroup(
            jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelRepLayout.setVerticalGroup(
            jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLogOutLayout = new javax.swing.GroupLayout(jPanelLogOut);
        jPanelLogOut.setLayout(jPanelLogOutLayout);
        jPanelLogOutLayout.setHorizontalGroup(
            jPanelLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelLogOutLayout.setVerticalGroup(
            jPanelLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                    .addComponent(jPanelSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelWel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanelPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanelPur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanelTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jPanelLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanelAddExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelWel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelDep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanelPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanelPur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanelTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAddExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEmpMouseClicked

tabEmp.setBackground(new Color(153,153,153));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


//tab4.setBackground(Color.BLACK);
jPanelEmp.setVisible(true);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);

//jPanel4.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_tabEmpMouseClicked

    private void tabDepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDepMouseClicked

tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(153,153,153));
tabSup.setBackground(new Color(0,153,204));  
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(true);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);
//jPanel4.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_tabDepMouseClicked

    private void tabSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSupMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(153,153,153));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(true);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);
//jPanel4.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_tabSupMouseClicked

    private void tabWelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabWelMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(153,153,153));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(true);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_tabWelMouseClicked

    private void tabAttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAttMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(153,153,153));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(true);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_tabAttMouseClicked

    private void tabPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPayMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(153,153,153));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(true);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_tabPayMouseClicked

    private void tabPurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPurMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(153,153,153));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(true);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_tabPurMouseClicked

    private void tabTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTraMouseClicked
        // TODO add your handling code here:
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(153,153,153));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(true);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false); 
    }//GEN-LAST:event_tabTraMouseClicked

    private void tabRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabRepMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(153,153,153));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(true);
jPanelLogOut.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_tabRepMouseClicked

    private void tabLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLogOutMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(153,153,153));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_tabLogOutMouseClicked

    private void tabLvsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLvsMouseClicked
    
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(153,153,153));
tabPay.setBackground(new Color(0,153,204));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(true);
jPanelPay.setVisible(false);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_tabLvsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
    jLabel13.setForeground(Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
   // jLabel13.setForeground(Color.153); 
//   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
      jButton5.setForeground(new Color(0,0,0));   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {
            // Perform deletion logic here
            JOptionPane.showMessageDialog(null, "Item deleted.", "Deletion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // User clicked "No" or closed the dialog
            JOptionPane.showMessageDialog(null, "Deletion canceled.", "Deletion", JOptionPane.INFORMATION_MESSAGE);
        }
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tabAddExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAddExpMouseClicked
tabEmp.setBackground(new Color(0,153,204));
tabDep.setBackground(new Color(0,153,204));
tabSup.setBackground(new Color(0,153,204));
tabWel.setBackground(new Color(0,153,204));
tabAtt.setBackground(new Color(0,153,204));
tabLvs.setBackground(new Color(0,153,204));
tabPay.setBackground(new Color(0,153,204));
tabAddExp.setBackground(new Color(153,153,153));
tabPur.setBackground(new Color(0,153,204));
tabTra.setBackground(new Color(0,153,204));
tabRep.setBackground(new Color(0,153,204));
tabLogOut.setBackground(new Color(0,153,204));


jPanelEmp.setVisible(false);
jPanelDep.setVisible(false);
jPanelSup.setVisible(false);
jPanelWel.setVisible(false);
jPanelAtt.setVisible(false);
jPanelLvs.setVisible(false);
jPanelPay.setVisible(false);
jPanelAddExp.setVisible(true);
jPanelPur.setVisible(false);
jPanelTra.setVisible(false);
jPanelRep.setVisible(false);
jPanelLogOut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_tabAddExpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAddExp;
    private javax.swing.JPanel jPanelAtt;
    private javax.swing.JPanel jPanelDep;
    private javax.swing.JPanel jPanelEmp;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLogOut;
    private javax.swing.JPanel jPanelLvs;
    private javax.swing.JPanel jPanelPay;
    private javax.swing.JPanel jPanelPur;
    private javax.swing.JPanel jPanelRep;
    private javax.swing.JPanel jPanelSup;
    private javax.swing.JPanel jPanelTab;
    private javax.swing.JPanel jPanelTra;
    private javax.swing.JPanel jPanelWel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel tabAddExp;
    private javax.swing.JPanel tabAtt;
    private javax.swing.JPanel tabDep;
    private javax.swing.JPanel tabEmp;
    private javax.swing.JPanel tabLogOut;
    private javax.swing.JPanel tabLvs;
    private javax.swing.JPanel tabPay;
    private javax.swing.JPanel tabPur;
    private javax.swing.JPanel tabRep;
    private javax.swing.JPanel tabSup;
    private javax.swing.JPanel tabTra;
    private javax.swing.JPanel tabWel;
    // End of variables declaration//GEN-END:variables
}
